.hy
.TH "exa" "1" "2015\-10\-18" "exa 0.4.0" ""
.SH NAME
.PP
exa \- a modern replacement for ls
.SH SYNOPSIS
.PP
exa [\f[I]options\f[]] [\f[I]files\f[]]...
.SH DESCRIPTION
.PP
\f[C]exa\f[] is a modern replacement for \f[C]ls\f[].
It uses colours for information by default, helping you distinguish
between many types of files, such as whether you are the owner, or in
the owning group.
It also has extra features not present in the original \f[C]ls\f[], such
as viewing the Git status for a directory, or recursing into directories
with a tree view.
.SH DISPLAY OPTIONS
.TP
.B \-1, \-\-oneline
display one entry per line
.RS
.RE
.TP
.B \-G, \-\-grid
display entries in a grid view (default)
.RS
.RE
.TP
.B \-l, \-\-long
display extended details and attributes
.RS
.RE
.TP
.B \-R, \-\-recurse
recurse into directories
.RS
.RE
.TP
.B \-T, \-\-tree
recurse into subdirectories in a tree view
.RS
.RE
.TP
.B \-x, \-\-across
sort multi\-column view entries across
.RS
.RE
.TP
.B \-\-color, \-\-colour=\f[I]WHEN\f[]
when to colourise the output (always, automatic, never)
.RS
.RE
.SH FILTERING AND SORTING OPTIONS
.TP
.B \-a, \-\-all
show dot\-files
.RS
.RE
.TP
.B \-d, \-\-list\-dirs
list directories as regular files
.RS
.RE
.TP
.B \-r, \-\-reverse
reverse order of files
.RS
.RE
.TP
.B \-s, \-\-sort=\f[I]WORD\f[]
field to sort by (name, size, extension, modified, accessed, created,
inode, none)
.RS
.RE
.TP
.B \-\-group\-directories\-first
list directories before other files
.RS
.RE
.SH LONG VIEW OPTIONS
.PP
These options are available when running with \f[C]\-\-long\f[]
(\f[C]\-l\f[]):
.TP
.B \-b, \-\-binary
use binary prefixes in file sizes
.RS
.RE
.TP
.B \-B, \-\-bytes
list file sizes in bytes, without prefixes
.RS
.RE
.TP
.B \-g, \-\-group
show group as well as user
.RS
.RE
.TP
.B \-h, \-\-header
show a header row at the top
.RS
.RE
.TP
.B \-H, \-\-links
show number of hard links
.RS
.RE
.TP
.B \-i, \-\-inode
show each file\[aq]s inode number
.RS
.RE
.TP
.B \-L, \-\-level=\f[I]DEPTH\f[]
maximum depth of recursion
.RS
.RE
.TP
.B \-m, \-\-modified
display timestamp of most recent modification
.RS
.RE
.TP
.B \-S, \-\-blocks
show number of file system blocks
.RS
.RE
.TP
.B \-t, \-\-time=\f[I]WORD\f[]
which timestamp to show for a file (modified, accessed, created)
.RS
.RE
.TP
.B \-u, \-\-accessed
display timestamp of last access for a file
.RS
.RE
.TP
.B \-U, \-\-created
display timestamp of creation for a file
.RS
.RE
.TP
.B \-\@, \-\-extended
display extended attribute keys and sizes
.RS
.RE
.TP
.B \-\-git
display Git status for a file, if available
.RS
.RE
.SH EXAMPLES
.PP
To display a list of files, with the largest at the top:
.IP
.nf
\f[C]
exa\ \-\-reverse\ \-\-sort=size
\f[]
.fi
.PP
To display a tree of files, three levels deep:
.IP
.nf
\f[C]
exa\ \-\-long\ \-\-tree\ \-\-level=3
\f[]
.fi
.SH AUTHOR
.PP
\f[C]exa\f[] is maintained by Benjamin \[aq]ogham\[aq] Sago and many
other contributors.
You can view the full list at
<https://github.com/ogham/exa/graphs/contributors>.
