name: Unit tests

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'Cargo.*'
      - build.rs
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'Cargo.*'
      - build.rs

env:
  CARGO_TERM_COLOR: always

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}

    continue-on-error: ${{ matrix.rust == 'nightly' }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [1.66.1, stable, beta, nightly]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - name: Install cargo-hack
        run: cargo install cargo-hack@0.5.27

      - name: Run unit tests
        run: cargo hack test --feature-powerset
